### PR TITLE
Use collectd_config role and dynamic template generation

### PR DESCRIPTION
**Pull request by leifmadsen**
- Bump base image to 0.16.0
- Build ConfigMap using collectd_config role
- Add collectd_config role

### CODE REVIEW

**Comment by leifmadsen** [comment]
This is still very much a work in progress, but hoping to get around to cleaning a bunch of this up tomorrow. Right now I'm mixing my former work on minikube (stock k8s) and OpenShift environment in the documentation. Going to need to pick one or the other, or do a better job breaking this out.

I did manage to get this all working though and seeing data scraped by Prometheus for all the OpenShift nodes.

**Comment by leifmadsen** [comment]
Also add label trick so that k8s resource name is added as a label to the DaemonSet so the pods will restart on configmap change.

**Comment by leifmadsen** [comment]
[Update collectd-operator to fully working status so that it can be deployed into the Barometer lab for Intel TAS testing](https://trello.com/c/8XvJgqQr/1088-update-collectd-operator-to-fully-working-status-so-that-it-can-be-deployed-into-the-barometer-lab-for-intel-tas-testing)

**Review by elfiesmelfie — APPROVED** [review]
Looks okay to me, when I was testing this previously, I used crc and subbed kubectl with oc and it worked fine.

**Pull request merged**
